// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.Map;

import static org.junit.Assert.*;
public class ValidarlafuncionalidadTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver");
    driver = new ChromeDriver();

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void validarlafuncionalidad() {
    driver.get("http://automationpractice.com/index.php?controller=contact");
    driver.manage().window().setSize(new Dimension(1294, 741));
    {
      WebElement dropdown = driver.findElement(By.id("id_contact"));
      dropdown.findElement(By.xpath("//option[. = 'Customer service']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("id_contact"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("id_contact"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("id_contact"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("id_contact")).click();
    driver.findElement(By.id("message")).click();
    driver.findElement(By.id("message")).sendKeys("Mensaje de prueba");
    driver.findElement(By.cssSelector("#submitMessage > span")).click();
  }
}
